---
# tasks file for nginxphpfpm
- name: Install Prerequisites
  apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
  loop: ["aptitude"]

- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: ["nginx", "php-fpm"]

- name: Create a directory if it does not exist
  file:
    path: /opt/nginx/ansible
    state: directory
    mode: "0755"

- name: Sets Nginx conf file
  template:
    src: "files/nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ http_conf }}"

- name: Enables new site
  file:
    src: "/etc/nginx/sites-available/{{ http_conf }}"
    dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
    state: link
  notify: Restart Nginx

- name: Removes "default" site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx

- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

- name: Sets Up PHP Info Page
  template:
    src: "files/info.php.j2"
    dest: "/opt/nginx/ansible/index.php"
