---
- hosts: test
  become: true
  tasks:
    - name: Install postfix
      apt:
        name: postfix
        state: present
      tags:
      - init
      - postfix

    - name: Remove "postfix" package
      apt:
        name: postfix
        state: absent
      tags:
      - drop
      - postfix












          - name: Copy config file with permissions
      copy:
        src: ./vsftpd.conf
        dest: /etc/vsftpd.conf
        owner: ivan
        mode: '0777'
